### ISSUE TITLE
Deletion in "My Results"

### ISSUE THREAD

**Issue by pontikos** [Eye2Gene/eye2gene_web_app#7]
Deletion doesn't work in "My Results":

```
Oops! Eye2Gene went wonky!
Apologies, there was an error with your request. Please try again.

Error Message: no implicit conversion of nil into String

If the error persists, please contact us viaemailor create an issue on githubhttps://github.com/Eye2Gene/eye2gene_web_app/issues/.
```

**Comment by IsmailM** [comment]
Updated server with Fix...

**Comment by IsmailM** [comment]
It’s a caching issue - updating the version number and rebuilding the assets should fix the issue …
I’ll do that in a bit...
via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=dx&cv=9.8.421&pv=10.13.6&source=email_footer_2]
On Sun, Sep 16, 2018 at 21:20, Nikolas Pontikos <notifications@github.com> wrote:
Reopened #7 [https://github.com/Eye2Gene/eye2gene_web_app/issues/7] .

**Comment by IsmailM** [comment]
have updated the servers - let me know if this is fixed for you?

**Comment by pontikos** [comment]
Yes!  Works now thank you!
